### ISSUE TITLE
Error NanoFilt

### ISSUE THREAD

**Issue by el-mat** [wdecoster/nanofilt#30] opened 2019-04-15 09:01 UTC
Hi,

I had successfully installed NanoFilt through ansible in a vdi but when it was installed in another environnement using the ansible-playbook the installation seems to be compromised. I get the following error when I try to launch NanoFilt:
"Traceback (most recent call last):
  File "/usr/local/bin/lmod/nanofilt/2.2.0/venv/bin/NanoFilt", line 6, in <module>
    from nanofilt.NanoFilt import main
  File "/usr/local/bin/lmod/nanofilt/2.2.0/venv/lib/python3.5/site-packages/nanofilt/NanoFilt.py", line 29, in <module>
    from nanoget import process_summary
ImportError: cannot import name 'process_summary'"

Do you have any idea what could cause this error?

Thank you very much.
Kind regards,
Elisabeth Mathijs

**Comment by wdecoster** [comment] 2019-04-15 09:08
Hi, 

This problem looks like a duplicate of https://github.com/wdecoster/nanofilt/issues/27
Can you try updating to NanoFilt 2.3.0? That should solve it...

Cheers,
Wouter

**Comment by el-mat** [comment] 2019-04-15 09:11
Hi Wouter,

OK I will try to update to 2.3.0. 

Thank you for your quick response.
Kind regards,
Elisabeth

**Comment by wdecoster** [comment] 2019-04-15 09:19
Alright, keep me posted!

**Comment by el-mat** [comment] 2019-04-15 09:53
Dear Wouter,
NanoFilt 2.3.0 seems to work fine. 
Thank you for your help.
Elisabeth

**Comment by wdecoster** [comment] 2019-04-15 09:55
Good to hear! Let me know if there is anything else I can help you with.

**Closed as completed by wdecoster** 2019-04-15 09:55 UTC
